node {
    def app

    environment {
        REACT_APP_BACKEND_WS     = 'ws://localhost:8080'
        REACT_APP_BACKEND_URL    = 'http://localhost:8080'
        NODE_ENV       = 'production'
    }
    stage('build') {
        echo "Starting Build"
        app = docker.build("stephanzbti/frontend-smarttbot")
        echo "Finishing Build"
    }
    stage('RepositoryImage') {
        echo "Starting Login Repository"
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            echo "Starting Push Image"
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
            echo "Finishing Push Image"
        }
        echo "Finishing Login Repository"
    }
}