version: "2"
services:
  backend-dev:
    build: ./backend/
    environment:
      - ALLOWED_ORIGIN=*
      - REDIS_ADDR=redis:6379
      - ENVIRONMENT=development
    ports: 
      - "8080:8080"
    depends_on: 
      - redis
  frontend-dev:
    build: ./frontend/
    environment:
      - REACT_APP_BACKEND_WS=ws://localhost:8080
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - NODE_ENV=development
    ports:
      - "3000:3000"
  redis:
    image: redis
    container_name: redis
    command: redis-server
    expose:
      - 6379