node {
    checkout scm

    def app
    environment {
        ALLOWED_ORIGIN = '*'
        REDIS_ADDR     = 'redis:6379'
        ENVIRONMENT    = 'production'
    }
    stage('build') {
        echo "Starting Build"
        app = docker.build("stephanzbti/backend-smarttbot")
        echo "Finishing Build"
    }
    stage('RepositoryImage') {
        echo "Starting Login Repository"
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            echo "Starting Push Image"
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
            echo "Finishing Push Image"
        }
        echo "Finishing Login Repository"
    }
}